name: Weekly cron

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"
  pull_request:
    # We also want this workflow triggered if the `Weekly CI` label is
    # added or present when PR is updated
    types:
      - synchronize
      - labeled
  workflow_dispatch:

jobs:
  data:
    if: (github.repository == 'spacetelescope/romanisim' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'Weekly CI')))
    uses: ./.github/workflows/data.yml
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    needs: [ data ]
    with:
      libraries: |
        brew:
          - eigen
          - fftw
      setenv: |
        WEBBPSF_PATH: ${{ needs.data.outputs.webbpsf_path }}
        GALSIM_CAT_PATH: ${{ needs.data.outputs.galsim_cat_path }}
        FFTW_DIR: /opt/homebrew/opt/fftw/lib/
      cache-path: ${{ needs.data.outputs.path }}
      cache-key: data-${{ needs.data.outputs.hash }}
      envs: |
        - macos: py310-xdist
        - macos: py311-xdist
        - linux: py3-devdeps-xdist
